# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Building M3U8-Downloader CI/CD

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node-version: [ 22.14.0 ]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
          yarn
          yarn ${{ matrix.os }}
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          dist/M3U8-Downloader-*
          !dist/M3U8-Downloader-*.blockmap
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
